### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by mmerino25** [atticus-sullivan/catppuccinPalette#3]
The documentation uploaded to CTAN shows every style with Latte Variant colors. However the catppuccin website shows that the others variants are different. Is this an issue with the CTAN documentation or the color are actually defined incorrectly?

**Comment by atticus-sullivan** [comment]
Oh I see. The colors are actually defined the right way, but there is a mistake in generating this table thing.

```latex
% \foreach \Style in {Latte,Frappe,Macchiato,Mocha}{
% \subsubsection{Style \texttt{\Style}}
% \begin{multicols}{2}
%  \def\Style{Latte}
%  \showCol{Cat\Style Blue}\par
```
I mean, the loop is nice, but if I set the "loop-variable" to Latte every iteration, it cannot possibly work.

Thanks for pointing this out.
